plugins:
  - plantuml:
      puml_url: https://www.plantuml.com/plantuml/
      num_workers: 8
  - search
  - mermaid2  # You can have both PlantUML and Mermaid

markdown_extensions:
  - plantuml_markdown:
      server: https://www.plantuml.com/plantuml