name: Deploy Eleventy to GitHub Pages

on:
  # Manual trigger with deployment type selection
  workflow_dispatch:
    inputs:
      deployment_type:
        description: 'Deployment Type'
        required: true
        default: 'private'
        type: choice
        options:
          - private
          - public
      custom_url:
        description: 'Custom URL (optional, for private deployments)'
        required: false
        default: ''
        type: string

  # Automatic trigger on push to main (optional - remove if you want manual-only)
  # push:
  #   branches: [main]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build site for Private Deployment
        if: github.event.inputs.deployment_type == 'private' || github.event_name == 'push'
        env:
          # No path prefix for private deployment
          ELEVENTY_PATH_PREFIX: "/"
          URL: ${{ github.event.inputs.custom_url || '' }}
        run: |
          echo "Building for private GitHub Pages deployment..."
          echo "Path prefix: / (root)"
          npm run build:private

      - name: Build site for Public Deployment
        if: github.event.inputs.deployment_type == 'public'
        env:
          # Path prefix required for public deployment
          URL: "https://scotaccount.github.io/sg-identity-techdocs/"
          ELEVENTY_PATH_PREFIX: "/sg-identity-techdocs/"
        run: |
          echo "Building for public GitHub Pages deployment..."
          echo "Path prefix: /sg-identity-techdocs/"
          npm run build:public

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site